version: '3'
services:
  db:
    image: gcr.io/cloudsql-docker/gce-proxy:1.11
    command: /cloud_sql_proxy -instances ${INSTANCES}
    ports:
    - '3306:3306'
    volumes:
    - ~/.config/gcloud:/root/.config/gcloud
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - '8080:80'

